// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNWdf_ZgjwSQYhjxX9-yKhHrp1zZCEEgc',
    appId: '1:1036329119897:web:a30fc07d14682036dc0808',
    messagingSenderId: '1036329119897',
    projectId: 'pointalarm-df6af',
    authDomain: 'pointalarm-df6af.firebaseapp.com',
    storageBucket: 'pointalarm-df6af.firebasestorage.app',
    measurementId: 'G-1PK6Q6DGTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0B18e9gBVLopI6MTICbetYO3pvM9sX30',
    appId: '1:1036329119897:android:f5a5bf977aa3f544dc0808',
    messagingSenderId: '1036329119897',
    projectId: 'pointalarm-df6af',
    storageBucket: 'pointalarm-df6af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5_1Wy3ESOJ_ZKTLJTVvJx7bB24gagsB0',
    appId: '1:1036329119897:ios:e4406f1301df4e50dc0808',
    messagingSenderId: '1036329119897',
    projectId: 'pointalarm-df6af',
    storageBucket: 'pointalarm-df6af.firebasestorage.app',
    iosBundleId: 'com.example.pointAlarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5_1Wy3ESOJ_ZKTLJTVvJx7bB24gagsB0',
    appId: '1:1036329119897:ios:e4406f1301df4e50dc0808',
    messagingSenderId: '1036329119897',
    projectId: 'pointalarm-df6af',
    storageBucket: 'pointalarm-df6af.firebasestorage.app',
    iosBundleId: 'com.example.pointAlarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNWdf_ZgjwSQYhjxX9-yKhHrp1zZCEEgc',
    appId: '1:1036329119897:web:d7d53211ad4fed5fdc0808',
    messagingSenderId: '1036329119897',
    projectId: 'pointalarm-df6af',
    authDomain: 'pointalarm-df6af.firebaseapp.com',
    storageBucket: 'pointalarm-df6af.firebasestorage.app',
    measurementId: 'G-8HRDYM03ZZ',
  );

}